### PR TITLE
Added input validation & unit tests

### PR DESCRIPTION
**Pull request by marvinbuss**
- [x] Added first unit tests
- [x] Added validation test

### CODE REVIEW

**Comment by marvinbuss** [comment]
@awmatheson 

- [ ] fix input validation bug
- [ ] add additional tests

**Comment by marvinbuss** [comment]
@awmatheson Please review and test with different inputs. Feel free to add additional unit tests. I will also test tomorrow.

**Comment by awmatheson** [comment]
I had split the test and lint because I thought it might be clearer on the checks, but also fine to leave it as one.

**Comment by awmatheson** [comment]
@marvinbuss I noticed that the validation will not raise any error with missing or misspelled required field for the workspace.json. I added the required fields so that they matched the Readme.md and added a test to check for this.

**Comment by marvinbuss** [comment]
- [ ] Switch to SDK 1.4.0

**Comment by marvinbuss** [comment]
@awmatheson The parameters are not actually required, if the user sets things up correctly. The documentation is not correct. Should we change the JSON or the documentation?

**Pull request merged**
